spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.79:3306/dbgirl
    username: root
    password: zhaozhengyun
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jedis :
  pool :
    host : 192.168.2.79
    port : 6379
    password: zhaozhengyun
    timeout: 0
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000

